// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMiXMMN17qIQnVW5VfYuYKKhyE7S52SQ',
    appId: '1:1023987454059:web:1ca5a2ac9a49e5fb54612e',
    messagingSenderId: '1023987454059',
    projectId: 'academyesport-6d086',
    authDomain: 'academyesport-6d086.firebaseapp.com',
    storageBucket: 'academyesport-6d086.appspot.com',
    measurementId: 'G-KJZRLVVHKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznygDZ_Zu1r5GTkGOMIiNPtfsT1520oM',
    appId: '1:1023987454059:android:f8b3db4e9ff4053354612e',
    messagingSenderId: '1023987454059',
    projectId: 'academyesport-6d086',
    storageBucket: 'academyesport-6d086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAnhQgLRl6cGMY073-SiFZBXYmXP_-sA',
    appId: '1:1023987454059:ios:91a5ab7cafd1213954612e',
    messagingSenderId: '1023987454059',
    projectId: 'academyesport-6d086',
    storageBucket: 'academyesport-6d086.appspot.com',
    iosClientId: '1023987454059-c6u76o19ms6tohbv7bbkgl5bgjni31qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.yildizlar',
  );
}
